name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  badges: ^2.0.3
  adaptive_breakpoints: ^0.1.4
  adaptive_components: ^0.0.7
  adaptive_navigation: ^0.0.7
  animations: ^2.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  desktop_window: ^0.4.0
  dynamic_color: ^1.4.0
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  google_fonts: ^3.0.1
  material_color_utilities: ^0.1.4
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.5
  footer: ^0.0.4
  sticky_footer_scrollview: ^1.1.1
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "assets/background_icon.png"
  adaptive_icon_foreground: "assets/favicon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "##d3d7db"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/favicon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/favicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
